# Generated by Django 3.2.9 on 2022-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
