# Generated by Django 3.2.7 on 2021-09-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('productImage', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('customer_order_notes', models.CharField(max_length=5000, null=True)),
                ('internal_order_notes', models.CharField(max_length=5000, null=True)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.basket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrishShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=102, verbose_name='Contact name')),
                ('company_name', models.CharField(max_length=102, null=True, verbose_name='Company name')),
                ('address_line1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('address_line3', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 3')),
                ('eir_code', models.CharField(max_length=8, verbose_name='Eir Code')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrishBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=102, verbose_name='Contact name')),
                ('company_name', models.CharField(max_length=102, null=True, verbose_name='Company name')),
                ('address_line1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('address_line3', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 3')),
                ('eir_code', models.CharField(max_length=8, verbose_name='Eir Code')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.basket')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
