# Generated by Django 3.2.7 on 2021-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NotReceived', 'Not Received'), ('Received', 'Received')], default='NotReceived', max_length=32),
        ),
    ]
