# Generated by Django 3.2.7 on 2021-10-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211005_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irishbillingaddress',
            options={'verbose_name_plural': 'Irish Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='irishshippingaddress',
            options={'verbose_name_plural': 'Irish Shipping Addresses'},
        ),
    ]
