# Generated by Django 4.0.2 on 2022-02-18 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='last_store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiuser',
            name='store_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
            preserve_default=False,
        ),
    ]
