# Generated by Django 3.2.9 on 2021-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
