# Generated by Django 4.0.2 on 2022-03-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_apiuser_last_store_apiuser_store_login_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='basket',
            name='store_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
    ]
