# Generated by Django 4.0.2 on 2022-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_store_basket_store_id_order_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='user_image',
            field=models.FileField(default='images/user_images/defaultUser.jpg', upload_to='images/user_images/'),
        ),
    ]
