# Generated by Django 3.2.9 on 2021-12-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_basketitem_basketitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
