# Generated by Django 4.0.2 on 2022-03-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_apiuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='last_store',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
    ]
