# Generated by Django 4.0.2 on 2022-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_apiuser_last_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='store_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
