# Generated by Django 4.0.3 on 2022-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_line1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='store',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='store',
            name='eir_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Eir Code'),
        ),
    ]
