# Generated by Django 3.2.9 on 2021-12-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
