# Generated by Django 3.2.9 on 2021-12-13 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_basket_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
