# Generated by Django 4.0.3 on 2022-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_store_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Store_Basket_Item_limit',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='Store_Basket_Value_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=6, null=True),
        ),
    ]
