# Generated by Django 4.0.2 on 2022-04-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_apiuser_owned_store_alter_apiuser_last_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='last_store',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='owned_store',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='shop.store'),
        ),
    ]
