# Generated by Django 4.0.3 on 2022-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_apiuser_last_store_alter_apiuser_owned_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='storelogo_image',
            field=models.FileField(default='images/user_images/defaultstorelogo.png', upload_to='images/storelogo_images/'),
        ),
    ]
