# Generated by Django 4.0.3 on 2022-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_store_storelogo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storelogo_image',
            field=models.FileField(default='images/storelogo_images/defaultstorelogo.png', upload_to='images/storelogo_images/'),
        ),
    ]
