# Generated by Django 4.0.3 on 2022-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_store_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='POS_API_Publishable_Key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='POS_API_Secret_Key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
