# Generated by Django 4.0.2 on 2022-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_store_pos_api_publishable_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(default='stripe', max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='POS_API_Publishable_Key',
            field=models.CharField(blank=True, default='DEFAULT', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='POS_API_Secret_Key',
            field=models.CharField(blank=True, default='DEFAULT', max_length=1024, null=True),
        ),
    ]
